/**
 * MCP Config Manager
 * Handles .env file creation and manager configuration in config/progs
 */

import * as vscode from 'vscode';
import * as path from 'path';
import * as fs from 'fs/promises';
import * as crypto from 'crypto';

const MCP_SERVER_DIR = 'javascript/mcpServer/mcpWinCCOA';
const DEFAULT_PORT = 3000;

export interface MCPConfiguration {
    token: string;
    port: number;
    mode: 'http' | 'stdio';
    tools: string[];
    field: string;
}

export class MCPConfigManager {
    private outputChannel: vscode.OutputChannel;

    constructor(outputChannel: vscode.OutputChannel) {
        this.outputChannel = outputChannel;
    }

    /**
     * Generate a secure random token
     */
    generateToken(): string {
        return crypto.randomBytes(32).toString('hex');
    }

    /**
     * Write .env configuration file
     */
    async writeEnvFile(projectPath: string, config: MCPConfiguration): Promise<void> {
        const envPath = path.join(projectPath, MCP_SERVER_DIR, '.env');
        
        this.outputChannel.appendLine('📝 Writing .env configuration...');

        const envContent = `# MCP Server Configuration for WinCC OA
# Generated by VS Code Extension on ${new Date().toISOString()}

# ====================
# REQUIRED SETTINGS
# ====================

# API Token for authentication
MCP_API_TOKEN=${config.token}

# ====================
# SERVER CONFIGURATION
# ====================

# Server Mode: 'http' or 'stdio'
MCP_MODE=${config.mode}

# HTTP Server Settings
MCP_HTTP_PORT=${config.port}
MCP_HTTP_HOST=0.0.0.0

# Authentication Type: 'bearer' or 'api-key'
MCP_AUTH_TYPE=bearer

# ====================
# SECURITY SETTINGS
# ====================

# Rate Limiting
RATE_LIMIT_ENABLED=true
RATE_LIMIT_WINDOW_MS=60000
RATE_LIMIT_MAX=100

# CORS Configuration
MCP_CORS_ENABLED=false
MCP_CORS_ORIGINS=*

# ====================
# WINCC OA SETTINGS
# ====================

# Field Configuration
WINCCOA_FIELD=${config.field}

# ====================
# TOOLS CONFIGURATION
# ====================

# Tools to load (comma-separated list)
TOOLS=${config.tools.join(',') || 'datapoints/dp_basic,manager/manager_list'}
`;

        await fs.writeFile(envPath, envContent, 'utf8');
        this.outputChannel.appendLine(`✅ .env file written to ${envPath}`);
    }

    /**
     * Add MCP Server manager to config/progs
     */
    async addManagerToProgs(projectPath: string, managerName: string = 'MCP'): Promise<void> {
        const progsPath = path.join(projectPath, 'config', 'progs');
        
        this.outputChannel.appendLine('📝 Adding manager to config/progs...');

        // Read existing progs file
        let progsContent = '';
        try {
            progsContent = await fs.readFile(progsPath, 'utf8');
        } catch {
            // File doesn't exist, create new
            this.outputChannel.appendLine('  Creating new config/progs file');
        }

        // Check if MCP manager already exists
        if (progsContent.includes('WCCOActrl') && progsContent.includes('javascript/mcpServer')) {
            this.outputChannel.appendLine('  MCP manager already configured');
            return;
        }

        // Add MCP manager entry
        const managerEntry = `\n# MCP Server (AI Integration)
WCCOActrl -num 1 -name ${managerName} javascript/mcpServer/mcpWinCCOA/build/index_http.js
`;

        progsContent += managerEntry;
        await fs.writeFile(progsPath, progsContent, 'utf8');
        
        this.outputChannel.appendLine('✅ Manager added to config/progs');
    }

    /**
     * Remove MCP Server manager from config/progs
     */
    async removeManagerFromProgs(projectPath: string): Promise<void> {
        const progsPath = path.join(projectPath, 'config', 'progs');
        
        this.outputChannel.appendLine('🗑️ Removing manager from config/progs...');

        try {
            let progsContent = await fs.readFile(progsPath, 'utf8');
            
            // Remove MCP manager lines
            const lines = progsContent.split('\n');
            const filtered = lines.filter(line => 
                !line.includes('javascript/mcpServer') && 
                !line.includes('# MCP Server')
            );
            
            await fs.writeFile(progsPath, filtered.join('\n'), 'utf8');
            this.outputChannel.appendLine('✅ Manager removed from config/progs');
        } catch (error) {
            this.outputChannel.appendLine(`⚠️ Could not remove manager: ${error}`);
        }
    }

    /**
     * Read current MCP configuration
     */
    async readConfig(projectPath: string): Promise<MCPConfiguration | null> {
        const envPath = path.join(projectPath, MCP_SERVER_DIR, '.env');
        
        try {
            const envContent = await fs.readFile(envPath, 'utf8');
            
            // Parse .env file
            const config: MCPConfiguration = {
                token: this.extractEnvValue(envContent, 'MCP_API_TOKEN') || '',
                port: parseInt(this.extractEnvValue(envContent, 'MCP_HTTP_PORT') || '3000'),
                mode: (this.extractEnvValue(envContent, 'MCP_MODE') || 'http') as 'http' | 'stdio',
                tools: (this.extractEnvValue(envContent, 'TOOLS') || '').split(',').filter(Boolean),
                field: this.extractEnvValue(envContent, 'WINCCOA_FIELD') || 'default'
            };
            
            return config;
        } catch {
            return null;
        }
    }

    /**
     * Extract value from .env content
     */
    private extractEnvValue(content: string, key: string): string | null {
        const regex = new RegExp(`^${key}=(.*)$`, 'm');
        const match = content.match(regex);
        return match ? match[1].trim() : null;
    }

    /**
     * Get default tool configurations
     */
    getDefaultTools(): { name: string; tools: string[] }[] {
        return [
            {
                name: 'Read-Only Monitoring',
                tools: ['datapoints/dp_basic', 'archive/archive_query', 'manager/manager_list']
            },
            {
                name: 'Basic Control',
                tools: ['datapoints/dp_basic', 'datapoints/dp_set', 'manager/manager_list', 'manager/manager_control']
            },
            {
                name: 'Full Features',
                tools: [
                    'datapoints/dp_basic', 'datapoints/dp_set', 'datapoints/dp_create',
                    'opcua/opcua_connection', 'dashboards/dashboard', 'dashboards/widget',
                    'manager/manager_list', 'manager/manager_control'
                ]
            }
        ];
    }
}
